markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: lixiang0
author: "Ruben"
email: lingyunzi09#gmail.com
name: "My Blog"
url: http://blog.youran.ai
domain: blog.youran.ai
all_categories: [
["Deep Learning", "深度学习","/posts/dl.html"],
["Machine Learning", "机器学习","/posts/ml.html"], 
["nlp", "自然语言处理","/posts/nlp.html"],
["kg", "知识图谱","/posts/kg.html"],
["cpp", "C++","/posts/cpp.html"],
["python", "Python","/posts/python.html"],
["other", "杂记","/posts/other.html"],
["translation", "翻译","/posts/translation.html"],
["finance", "经济","/posts/finance.html"],
["about", "关于","/404.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: China/Shanghai

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
